//! Shared asynchronous quit barrier for native menu, Cmd-Q and tray requests.
use std::future::Future;
use std::sync::{
    Arc,
    atomic::{AtomicU8, Ordering},
};

const RUNNING: u8 = 0;
const STOPPING: u8 = 1;
const READY: u8 = 2;

#[derive(Clone, Default)]
pub(crate) struct ExitBarrier(Arc<AtomicU8>);

impl ExitBarrier {
    pub(crate) fn is_exiting(&self) -> bool {
        self.0.load(Ordering::Acquire) != RUNNING
    }

    pub(crate) fn request(
        &self,
        prevent: impl FnOnce(),
        cleanup: impl Future<Output = ()> + Send + 'static,
        exit: impl FnOnce() + Send + 'static,
    ) {
        // READY is published only after owned children have been reaped/unlocked.
        // The second ExitRequested generated by app.exit() must pass through.
        if self.0.load(Ordering::Acquire) == READY {
            return;
        }
        prevent();
        if self
            .0
            .compare_exchange(RUNNING, STOPPING, Ordering::AcqRel, Ordering::Acquire)
            .is_err()
        {
            return;
        }
        let phase = self.0.clone();
        tauri::async_runtime::spawn(async move {
            cleanup.await;
            phase.store(READY, Ordering::Release);
            exit();
        });
    }
}
